/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { BasicConfiguration, ModelConfiguration, Subscription, SubscriptionResult, TransactionConfiguration } from "../models/index";
import {
  BasicConfigurationFromJSON,
  BasicConfigurationToJSON,
  ModelConfigurationFromJSON,
  ModelConfigurationToJSON,
  SubscriptionFromJSON,
  SubscriptionResultFromJSON,
  SubscriptionResultToJSON,
  SubscriptionToJSON,
  TransactionConfigurationFromJSON,
  TransactionConfigurationToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface AddSubscriptionRequest {
  accountId: string;
  subscription?: Subscription;
}

export interface GenerateSubsciptionTokenRequest {
  accountId: string;
}

export interface GetConfigurationRequest {
  accountId: string;
}

export interface UpdateBasicConfigurationRequest {
  accountId: string;
  basicConfiguration?: BasicConfiguration;
}

export interface UpdateTransactionConfigurationRequest {
  accountId: string;
  transactionConfiguration?: TransactionConfiguration;
}

/**
 *
 */
export class ConfigurationApi extends runtime.BaseAPI {
  /**
   * Add subscription to the specified account with key
   */
  async addSubscriptionRaw(
    requestParameters: AddSubscriptionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ModelConfiguration>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling addSubscription().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/account/{accountId}/subscribe`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: SubscriptionToJSON(requestParameters["subscription"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ModelConfigurationFromJSON(jsonValue));
  }

  /**
   * Add subscription to the specified account with key
   */
  async addSubscription(requestParameters: AddSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelConfiguration> {
    const response = await this.addSubscriptionRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Genearte subscription token for a specified account
   */
  async generateSubsciptionTokenRaw(
    requestParameters: GenerateSubsciptionTokenRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SubscriptionResult>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling generateSubsciptionToken().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/subscription/token`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionResultFromJSON(jsonValue));
  }

  /**
   * Genearte subscription token for a specified account
   */
  async generateSubsciptionToken(requestParameters: GenerateSubsciptionTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionResult> {
    const response = await this.generateSubsciptionTokenRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get the current configuration
   */
  async getConfigurationRaw(
    requestParameters: GetConfigurationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ModelConfiguration>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling getConfiguration().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/configuration`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ModelConfigurationFromJSON(jsonValue));
  }

  /**
   * Get the current configuration
   */
  async getConfiguration(requestParameters: GetConfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelConfiguration> {
    const response = await this.getConfigurationRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Update currency and loginWithoutPassword configuration for a specified account
   */
  async updateBasicConfigurationRaw(
    requestParameters: UpdateBasicConfigurationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ModelConfiguration>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling updateBasicConfiguration().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/account/{accountId}/configuration`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: BasicConfigurationToJSON(requestParameters["basicConfiguration"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ModelConfigurationFromJSON(jsonValue));
  }

  /**
   * Update currency and loginWithoutPassword configuration for a specified account
   */
  async updateBasicConfiguration(requestParameters: UpdateBasicConfigurationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelConfiguration> {
    const response = await this.updateBasicConfigurationRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get the current configuration
   */
  async updateTransactionConfigurationRaw(
    requestParameters: UpdateTransactionConfigurationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ModelConfiguration>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling updateTransactionConfiguration().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/account/{accountId}/configuration/transaction`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: TransactionConfigurationToJSON(requestParameters["transactionConfiguration"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ModelConfigurationFromJSON(jsonValue));
  }

  /**
   * Get the current configuration
   */
  async updateTransactionConfiguration(
    requestParameters: UpdateTransactionConfigurationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ModelConfiguration> {
    const response = await this.updateTransactionConfigurationRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
