/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CreationTransaction, Transaction } from "../models/index";
import { CreationTransactionFromJSON, CreationTransactionToJSON, TransactionFromJSON, TransactionToJSON } from "../models/index";
import * as runtime from "../runtime";

export interface CreateOneTransactionRequest {
  accountId: string;
  walletId: string;
  creationTransaction?: CreationTransaction;
}

export interface GetAllTransactionsRequest {
  accountId: string;
  walletId?: string;
  startingDate?: Date;
  endingDate?: Date;
  type?: GetAllTransactionsTypeEnum;
  label?: Array<string>;
  minAmount?: number;
  maxAmount?: number;
  sortBy?: GetAllTransactionsSortByEnum;
  sort?: GetAllTransactionsSortEnum;
}

export interface GetOneTransactionRequest {
  accountId: string;
  walletId: string;
  transactionId: string;
}

export interface RemoveOneTransactionRequest {
  accountId: string;
  walletId: string;
  transactionId: string;
}

export interface UpdateOneTransactionRequest {
  accountId: string;
  walletId: string;
  transactionId: string;
  transaction?: Transaction;
}

/**
 *
 */
export class TransactionApi extends runtime.BaseAPI {
  /**
   * Create new transaction for the specified account
   */
  async createOneTransactionRaw(
    requestParameters: CreateOneTransactionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Transaction>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling createOneTransaction().');
    }

    if (requestParameters["walletId"] == null) {
      throw new runtime.RequiredError("walletId", 'Required parameter "walletId" was null or undefined when calling createOneTransaction().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/account/{accountId}/wallet/{walletId}/transaction`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"walletId"}}`, encodeURIComponent(String(requestParameters["walletId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: CreationTransactionToJSON(requestParameters["creationTransaction"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => TransactionFromJSON(jsonValue));
  }

  /**
   * Create new transaction for the specified account
   */
  async createOneTransaction(requestParameters: CreateOneTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Transaction> {
    const response = await this.createOneTransactionRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get all disponibles transaction for the specified account
   */
  async getAllTransactionsRaw(
    requestParameters: GetAllTransactionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Transaction>>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling getAllTransactions().');
    }

    const queryParameters: any = {};

    if (requestParameters["walletId"] != null) {
      queryParameters["walletId"] = requestParameters["walletId"];
    }

    if (requestParameters["startingDate"] != null) {
      queryParameters["startingDate"] = (requestParameters["startingDate"] as any).toISOString();
    }

    if (requestParameters["endingDate"] != null) {
      queryParameters["endingDate"] = (requestParameters["endingDate"] as any).toISOString();
    }

    if (requestParameters["type"] != null) {
      queryParameters["type"] = requestParameters["type"];
    }

    if (requestParameters["label"] != null) {
      queryParameters["label"] = requestParameters["label"];
    }

    if (requestParameters["minAmount"] != null) {
      queryParameters["minAmount"] = requestParameters["minAmount"];
    }

    if (requestParameters["maxAmount"] != null) {
      queryParameters["maxAmount"] = requestParameters["maxAmount"];
    }

    if (requestParameters["sortBy"] != null) {
      queryParameters["sortBy"] = requestParameters["sortBy"];
    }

    if (requestParameters["sort"] != null) {
      queryParameters["sort"] = requestParameters["sort"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/transaction`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TransactionFromJSON));
  }

  /**
   * Get all disponibles transaction for the specified account
   */
  async getAllTransactions(requestParameters: GetAllTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Transaction>> {
    const response = await this.getAllTransactionsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get get one transaction by id for the specified account
   */
  async getOneTransactionRaw(requestParameters: GetOneTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Transaction>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling getOneTransaction().');
    }

    if (requestParameters["walletId"] == null) {
      throw new runtime.RequiredError("walletId", 'Required parameter "walletId" was null or undefined when calling getOneTransaction().');
    }

    if (requestParameters["transactionId"] == null) {
      throw new runtime.RequiredError("transactionId", 'Required parameter "transactionId" was null or undefined when calling getOneTransaction().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/wallet/{walletId}/transaction/{transactionId}`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"walletId"}}`, encodeURIComponent(String(requestParameters["walletId"])));
    urlPath = urlPath.replace(`{${"transactionId"}}`, encodeURIComponent(String(requestParameters["transactionId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => TransactionFromJSON(jsonValue));
  }

  /**
   * Get get one transaction by id for the specified account
   */
  async getOneTransaction(requestParameters: GetOneTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Transaction> {
    const response = await this.getOneTransactionRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Delete one transaction and update wallet amount
   */
  async removeOneTransactionRaw(
    requestParameters: RemoveOneTransactionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Transaction>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling removeOneTransaction().');
    }

    if (requestParameters["walletId"] == null) {
      throw new runtime.RequiredError("walletId", 'Required parameter "walletId" was null or undefined when calling removeOneTransaction().');
    }

    if (requestParameters["transactionId"] == null) {
      throw new runtime.RequiredError("transactionId", 'Required parameter "transactionId" was null or undefined when calling removeOneTransaction().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/account/{accountId}/wallet/{walletId}/transaction/{transactionId}`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"walletId"}}`, encodeURIComponent(String(requestParameters["walletId"])));
    urlPath = urlPath.replace(`{${"transactionId"}}`, encodeURIComponent(String(requestParameters["transactionId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => TransactionFromJSON(jsonValue));
  }

  /**
   * Delete one transaction and update wallet amount
   */
  async removeOneTransaction(requestParameters: RemoveOneTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Transaction> {
    const response = await this.removeOneTransactionRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Update one transaction by id for the specified account
   */
  async updateOneTransactionRaw(
    requestParameters: UpdateOneTransactionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Transaction>> {
    if (requestParameters["accountId"] == null) {
      throw new runtime.RequiredError("accountId", 'Required parameter "accountId" was null or undefined when calling updateOneTransaction().');
    }

    if (requestParameters["walletId"] == null) {
      throw new runtime.RequiredError("walletId", 'Required parameter "walletId" was null or undefined when calling updateOneTransaction().');
    }

    if (requestParameters["transactionId"] == null) {
      throw new runtime.RequiredError("transactionId", 'Required parameter "transactionId" was null or undefined when calling updateOneTransaction().');
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/account/{accountId}/wallet/{walletId}/transaction/{transactionId}`;
    urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters["accountId"])));
    urlPath = urlPath.replace(`{${"walletId"}}`, encodeURIComponent(String(requestParameters["walletId"])));
    urlPath = urlPath.replace(`{${"transactionId"}}`, encodeURIComponent(String(requestParameters["transactionId"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: TransactionToJSON(requestParameters["transaction"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => TransactionFromJSON(jsonValue));
  }

  /**
   * Update one transaction by id for the specified account
   */
  async updateOneTransaction(requestParameters: UpdateOneTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Transaction> {
    const response = await this.updateOneTransactionRaw(requestParameters, initOverrides);
    return await response.value();
  }
}

/**
 * @export
 */
export const GetAllTransactionsTypeEnum = {
  In: "IN",
  Out: "OUT",
} as const;
export type GetAllTransactionsTypeEnum = (typeof GetAllTransactionsTypeEnum)[keyof typeof GetAllTransactionsTypeEnum];
/**
 * @export
 */
export const GetAllTransactionsSortByEnum = {
  Date: "date",
  Amount: "amount",
} as const;
export type GetAllTransactionsSortByEnum = (typeof GetAllTransactionsSortByEnum)[keyof typeof GetAllTransactionsSortByEnum];
/**
 * @export
 */
export const GetAllTransactionsSortEnum = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetAllTransactionsSortEnum = (typeof GetAllTransactionsSortEnum)[keyof typeof GetAllTransactionsSortEnum];
